# Multidimensional Arrays in NumPy

NumPy arrays are rectangles in as many dimensions as you need.

In [1]:
import numpy as np

In [2]:
M = np.arange(2*4*3).reshape([2,4,3])
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

``M`` is a 3-dimensional "data cube" of size 2x4x3. We can access individual elements by subscripting:

In [9]:
np.arange(100)[0:5]

array([0, 1, 2, 3, 4])

In [13]:
M[:, 1:, 0 : 2]

array([[[ 3,  4],
        [ 6,  7],
        [ 9, 10]],

       [[15, 16],
        [18, 19],
        [21, 22]]])

Arithmetic operators work element-by-element for same-shape arrays.

You can also add/multiply/etc a single value that will be applied to every element.

In [14]:
M + M / 2.0

array([[[  0. ,   1.5,   3. ],
        [  4.5,   6. ,   7.5],
        [  9. ,  10.5,  12. ],
        [ 13.5,  15. ,  16.5]],

       [[ 18. ,  19.5,  21. ],
        [ 22.5,  24. ,  25.5],
        [ 27. ,  28.5,  30. ],
        [ 31.5,  33. ,  34.5]]])

In [23]:
M[:,0,1].reshape((2,1,1)) + M

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

## Array slicing

The subscript index notation can also be used to retrieve "slices" of a larger array instead of single values. Use a colon ":" character to specify a range or on its own as a placeholder to fetch an entire dimension.

In [24]:
M[1,:,:]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [25]:
s = M[1,:,0:2]
s

array([[12, 13],
       [15, 16],
       [18, 19],
       [21, 22]])

Array slices can be used as standalone arrays. But watch out! They are references into your original array, and changing them can change the original.

In [26]:
s * 10

array([[120, 130],
       [150, 160],
       [180, 190],
       [210, 220]])

In [27]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [28]:
s[:] = 0
s

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [29]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

Use the ``.copy()`` method to avoid this behavior:

In [30]:
S = M[0,:,:].copy()

In [31]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

In [32]:
S

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
S[:] = 10

In [34]:
S

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [35]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

In [36]:
M == 5

array([[[False, False, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]], dtype=bool)

In [41]:
M % 2 == 0

array([[[ True, False,  True],
        [False,  True, False],
        [ True, False,  True],
        [False,  True, False]],

       [[ True,  True,  True],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True, False]]], dtype=bool)

In [43]:
evens = M[M % 2 == 0]

In [44]:
evens = evens ** 2 + 10

In [45]:
evens

array([ 10,  14,  26,  46,  74, 110,  10,  10, 206,  10,  10,  10,  10,
       410,  10,  10])

In [46]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

In [48]:
M[M % 2 == 0] = evens

In [49]:
M

array([[[ 10,   1,  14],
        [  3,  26,   5],
        [ 46,   7,  74],
        [  9, 110,  11]],

       [[ 10,  10, 206],
        [ 10,  10,  17],
        [ 10,  10, 410],
        [ 10,  10,  23]]])